CREATE TABLE  "PLANNING" 
   (	"ID" NUMBER, 
	"CIVILITY" VARCHAR2(30), 
	"FIRST_NAME" VARCHAR2(30), 
	"LAST_NAME" VARCHAR2(30), 
	"ADDRESS" VARCHAR2(30), 
	"CITY" VARCHAR2(30), 
	"POSTAL_CODE" VARCHAR2(5), 
	"EMAIL" VARCHAR2(255), 
	"TELEPHONE" VARCHAR2(30), 
	"LATITUDE" NUMBER, 
	"LONGITUDE" NUMBER, 
	"START_DATE" DATE, 
	"FITTER" VARCHAR2(30), 
	"DURATION" NUMBER, 
	"GOLD" VARCHAR2(1), 
	"START_TS" TIMESTAMP (6)
   )
/
 CREATE SEQUENCE   "PLANNING_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 541 CACHE 20 NOORDER  NOCYCLE  NOKEEP  GLOBAL
/
CREATE OR REPLACE EDITIONABLE TRIGGER  "bi_PLANNING" 
  before insert on "PLANNING"              
  for each row 
begin  
  if :new."ID" is null then
    select "PLANNING_SEQ".nextval into :new."ID" from sys.dual;
  end if;
end;

/
ALTER TRIGGER  "bi_PLANNING" ENABLE
/
